#default: &default
#  adapter: postgresql
#  encoding: unicode
#  pool: 5
#  port: 5432
#  username: <%= ENV["DB_USERNAME"] %>
#  password: <%= ENV["DB_PASSWORD"] %>
#  database: <%= ENV["DB_NAME"] %>
#
#development:
#  <<: *default
#
#production:
#  <<: *default
#
#test:
#  <<: *default

development:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DB_NAME"] %>
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  # password: password

production:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DB_NAME"] %>
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>
  # password: password

test:
  adapter: postgresql
  encoding: unicode
  database: <%= ENV["DB_NAME"] %>
  pool: 5
  username: <%= ENV["DB_USERNAME"] %>